image: node:slim
cache:
  paths:
  - node_modules/
before_script:
  - npm install
stages:
  - build
  - test

build_job:
  stage: build
  script:
  - make build
  
curatorCIPipeline:
  stage: test
  script:
    - npm run lint
  only:
    - pushes
  tags:
    - curator